### ISSUE TITLE
How can i modify the index page?

### ISSUE THREAD

**Issue by misterzik** [IonicaBizau/web-term#16] opened 2015-08-19 18:42 UTC
Good Afternoon,

I am interested in building a small template on top of this beautiful app, you guys have created. I tried adding stuff to /node_modules/web-term/bin/public/index.html but i cannot see any changes.

Am i editing the right place? Also you guys rock for creating this web terminal \m/

Best Regards

**Comment by IonicaBizau** [comment] 2015-08-19 18:59
Hey @misterzik! 

Could you please explain what you're trying to do? Maybe such a feature would be nice to have it in `web-term` itself.

Editing `bin/public/index.html` should work.

Thanks! :sparkle:

**Comment by misterzik** [comment] 2015-08-19 19:14
Hey, @IonicaBizau ,

Thanks for the quick response, I would like to add a template with different background, just like your sample. (https://camo.githubusercontent.com/390c4ec78b874793d395344b383958f7626416cc/687474703a2f2f692e696d6775722e636f6d2f343946547066492e706e67) and perhaps add a few tabs , and a footer in html. 

I did edit the index, and close the terminal with ctrl + c, and re-ran web-term from the terminal but i cant see the changes ive made. 

I would also like to add a few more javascripts libraries (UI Stuff). Will share my progress once ive something going on. 

Thanks my friend

**Comment by IonicaBizau** [comment] 2015-08-19 19:16
The background color is editable from CSS. The other ones are HTML + CSS (probably there is some position:fixed/absolute element).

**Comment by IonicaBizau** [comment] 2015-08-20 05:11
@misterzik Here are some snippets:
- [Background color](https://github.com/IonicaBizau/web-term/blob/f95ce53a8eebca944131548e738ec6c426fc7d62/bin/public/css/style.css#L17)
- [`position:fixed` element](https://github.com/IonicaBizau/web-term/blob/f95ce53a8eebca944131548e738ec6c426fc7d62/bin/public/css/style.css#L18-L22)

**Comment by misterzik** [comment] 2015-08-20 13:20
@IonicaBizau Good morning, 

Thanks for the response, Yes that was the first thing i modified but my mistake was a bit more silly. 
I globally installed it, and also installed it on a different folder which is what i am testing on. SO! _PALM FACE_ i was modifying my root folder for my server instead of my /usr/local/lib/. I know epic fail.

So now that ive erase it from my global, and only have installed it on the folder for my apache, im not able to run the cmd > web-term anymore because i erased it from my global. How can i run this without installing it globally? is it possible?

**Comment by IonicaBizau** [comment] 2015-08-20 13:28
If you install it locally you could start it this way:

``` sh
./path/to/the/web-term/bin/web-term
```

Cool, yeah? :smile:

**Comment by misterzik** [comment] 2015-08-20 13:29
Thanks man, yeah i CD to the folder and ran it with ./ , I think im going to create a path for it, will send you the demo of my template when done. Thanks for your help my friend. :)

**Comment by IonicaBizau** [comment] 2015-08-20 13:29
Nice! You're welcome! :+1:

**Comment by misterzik** [comment] 2015-08-20 15:50
@IonicaBizau - is it possible to have two console runnings? within the same page. i went to web-term.js and modified it to 

```
$(document).ready(function() {
    $(".term1").webTerm();
);
```

i was wondering if doing this will help,

```
$(document).ready(function() {
    $(".term1").webTerm();
    $(".term2").webTerm();

);
```

and on the html call it inside the divs? would it work to get a new session of the console?

**Comment by IonicaBizau** [comment] 2015-08-20 15:52
Theoretically yes, practically I guess it's buggy. :smile: But it's supposed to work. Can you confirm that both sides become black?

Btw, you can use `tmux` for splitting.

**Comment by misterzik** [comment] 2015-08-20 16:44
@IonicaBizau Yes it's buggy :( i cant no longer type on the first window, and everything i write on the first one comes out on the second window! weird!

What i am trying to aim is to have multiple terminals, within the same page with different sections to be able to multitasks on different ssh accounts.

**Comment by misterzik** [comment] 2015-08-20 20:14
![woo](https://cloud.githubusercontent.com/assets/7330400/9394423/75eae7b0-4756-11e5-8f4d-31f3cc7ae68e.png) @IonicaBizau :) , still trying to figure it out, how to run multiple console with different sessions in the same page! thanks for help man.

Used api, 

```
$(".container2").webTerm().create();
```

when i type on the top one, i get the same from both,

![woo2](https://cloud.githubusercontent.com/assets/7330400/9394767/55e175c2-4758-11e5-883d-62aec8601c0b.png)

**Comment by IonicaBizau** [comment] 2015-08-21 05:38
The problem is that on the server there is _one_ terminal instance created. This should be fixed (contributions welcome!).

Will debug the things next week if you are not faster than me. :smile:

**Comment by misterzik** [comment] 2015-08-21 15:27
@IonicaBizau am i going in the right direction? https://github.com/misterzik/web-term/blob/master/lib/index.js xD

**Comment by IonicaBizau** [comment] 2015-08-21 15:30
@misterzik It's a good start, but not really a good solution. Not sure, but somewhere I think I there is a global (file-level) variable which has the terminal... But will give you some help in the next few minutes.... :smile:

**Comment by IonicaBizau** [comment] 2015-08-21 15:43
Ok, so, it's not really a  global, but we should change the code _a little_: to be able to create `WebTerm` instances like this: `var myTerm = new WebTerm()`–that will allow us to create how many terminals we want.

So, [here](https://github.com/IonicaBizau/web-term/blob/f95ce53a8eebca944131548e738ec6c426fc7d62/bin/web-term#L84) in the `bin` script we will define a variable `var terminal = null` and in the [`create` callback](https://github.com/IonicaBizau/web-term/blob/f95ce53a8eebca944131548e738ec6c426fc7d62/bin/web-term#L86) we will set the `terminal` value: `terminal = new WebTerm({ /* maybe some options */ })`. In the other callbacks `terminal` will be used instead of `WebTerm`.

Then, in the library file we will remove the [`new`  here](https://github.com/IonicaBizau/web-term/blob/f95ce53a8eebca944131548e738ec6c426fc7d62/lib/index.js#L87)–and call the `create` method [here](https://github.com/IonicaBizau/web-term/blob/f95ce53a8eebca944131548e738ec6c426fc7d62/lib/index.js#L13):

``` js
function WebTerm(options) {
    this.terminal = null;
    this.create(options);
}
```

(by the way, the `create` method doesn't need a callback function)

---

If everything will go smoothly, you just need to enjoy then! [Donations are always welcome](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=MG98D7NPFZ3MG), too! :four_leaf_clover:

**Comment by misterzik** [comment] 2015-08-21 19:06
@IonicaBizau thanks for the help, the server hung on me! and def will be sending something over paypal \m/ _cheers_

```
info  Successfully started the web term server: http://localhost:9000



Missing error handler on `socket`.
TypeError: object is not a function
at Socket.<anonymous> (/Web/Terminals/node_modules/web-term/bin/web-term:88:20)
at Socket.emit (events.js:118:17)
at Socket.onevent (/Web/Terminals/node_modules/web-term/node_modules/socket.io/lib/socket.js:330:8)
at Socket.onpacket (/Web/Terminals/node_modules/web-term/node_modules/socket.io/lib/socket.js:290:12)
at Client.ondecoded (/Web/Terminals/node_modules/web-term/node_modules/socket.io/lib/client.js:193:14)
at Decoder.Emitter.emit (/Web/Terminals/node_modules/web-term/node_modules/socket.io/node_modules/socket.io-parser/node_modules/component-emitter/index.js:134:20)
at Decoder.add (/Web/Terminals/node_modules/web-term/node_modules/socket.io/node_modules/socket.io-parser/index.js:247:12)
at Client.ondata (/Web/Terminals/node_modules/web-term/node_modules/socket.io/lib/client.js:175:18)
at Socket.emit (events.js:107:17)
at Socket.onPacket (/Web/Terminals/node_modules/web-term/node_modules/socket.io/node_modules/engine.io/lib/socket.js:99:14)
/Web/Terminals/node_modules/web-term/bin/web-term:120
    WebTerm.kill();
            ^
TypeError: undefined is not a function
at Socket.<anonymous> (/Web/Terminals/node_modules/web-term/bin/web-term:120:17)
at Socket.emit (events.js:107:17)
at Socket.emit (/Web/Terminals/node_modules/web-term/node_modules/socket.io/lib/socket.js:129:10)
at Socket.onclose (/Web/Terminals/node_modules/web-term/node_modules/socket.io/lib/socket.js:418:8)
at Client.onclose (/Web/Terminals/node_modules/web-term/node_modules/socket.io/lib/client.js:230:12)
at Client.onerror (/Web/Terminals/node_modules/web-term/node_modules/socket.io/lib/client.js:211:8)
at Client.ondata (/Web/Terminals/node_modules/web-term/node_modules/socket.io/lib/client.js:177:10)
at Socket.emit (events.js:107:17)
at Socket.onPacket (/Web/Terminals/node_modules/web-term/node_modules/socket.io/node_modules/engine.io/lib/socket.js:99:14)
at XHR.emit (events.js:107:17)
```

**Comment by IonicaBizau** [comment] 2015-08-22 17:54
@misterzik Please push the changes you did and open a pull request. I'm happy to fix the errors that still exist and see what's going on. Thanks! :dizzy:

**Comment by IonicaBizau** [comment] 2015-08-23 10:43
Please check out the `mulitple-terms` branch–hope you don't mind if I used `<iframe>`s to create multiple terminals. :smile: 

After starting the process you should be able to access `localhost:9000/vs` and `localhost:9000/hs` for split windows.

I guess you have to install some missing packages first (`npm i <package-name>`).

**Closed as completed** 2015-08-23 14:23 UTC
Labels: bug

**Comment by misterzik** [comment] 2015-08-23 18:14
@IonicaBizau w00t! sorry i took long, was away for the weekend, I am trying this right now, Installed all the dependencies, and pow! its work now!

Great work my friend, great work.. The fixes you gave me before it wasnt enough right? there was couple of dependencies to add? and by the way i will be uploading few themes, if anybody is interested feel free to get them.

**Comment by misterzik** [comment] 2015-08-23 18:36
sudo npm i ul
npm WARN package.json web-term@3.0.0 license should be a valid SPDX license expression

**Comment by IonicaBizau** [comment] 2015-08-24 06:58
@misterzik `npm i -g web-term@latest` should work well–you can check if it worked by running `web-term -v`. :dart: 

> Great work my friend, great work.. 

Thanks! :smile: 

> The fixes you gave me before it wasnt enough right?

Actually I think they were–maybe with some little adjustments. :bulb: But in 3.1.0 we now have one terminal/connection (that means one terminal per page). Before it was one terminal per server, which was good, but you just found the limitation. :smile_cat: 

>  and by the way i will be uploading few themes, if anybody is interested feel free to get them.

Fell free to create a pull request and add them. Maybe it would be interesting to have a way to include CSS files or so (maybe a file like `~/.web-term.json` which will contain the config?). But definitely, just add them and add yourself as contributor. :construction_worker:
