### ISSUE TITLE
"clear" and "CTRL + L" not working on some browsers

### ISSUE THREAD

**Issue by tmdroid** [IonicaBizau/web-term#5] opened 2015-02-05 14:40 UTC
I'm having a problem with the `clear` command. I get this error: 

``` sh
danny@TabletPC:~$ clear 
'Browser Term': unknown terminal type.
```

And <kbd>CTRL</kbd> + <kbd>L</kbd> works as a normal <kbd>Enter</kbd> key.

I'm using **Chromium 37.0.2062.120** on elementaryOS Luna.

**Comment by IonicaBizau** [comment] 2015-03-27 13:16
@csanonymus Check if this was fixed in the latest release (`npm i -g web-term@latest`).

**Comment by tmdroid** [comment] 2015-03-27 13:27
I still have the same issue

![ScreenShot](http://s7.postimg.org/hd5jf4v0b/Screenshot_from_2015_03_27_15_25_36.png)

**Comment by IonicaBizau** [comment] 2015-05-12 15:02
@csanonymus  We reproduced this issue in an internal @jillix application. The I applied is to export the `TERM` environment variable.

Run the following commands:

``` sh
echo "export TERM=xterm-256color" >> ~/.bashrc
source ~/.bashrc
```

Then the `web-term` experience will be smoother.

I will make sure I add this info in the `web-term` docs in the next release.

**Comment by IonicaBizau** [comment] 2015-05-12 15:14
Actually, just run `export TERM=xterm-256color` in the terminal session. I will try to force setting this environment variable in web-term.

However, I opened this issue: https://github.com/chjj/pty.js/issues/120 I'd :+1: for fixing it in the core library.

**Comment by IonicaBizau** [comment] 2015-05-12 17:57
This happened because of the custom `name`. I addressed this :bug: in https://github.com/IonicaBizau/web-term/commit/384c2a7f8cca2e8187a1bae55577c65950a92b94.

@csanonymus Would be glad if you test the `improvements` branch and give feedback! :sparkle:

**Comment by tmdroid** [comment] 2015-05-13 14:58
Yes, the branch solves the bug. Great job!

**Closed as completed** 2015-05-15 09:56 UTC
Labels: documentation
